[package]
name = "dynlib-rent-free"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sa-monopoly-application = { path = "../../crates/application" }
sa-monopoly-infra = { path = "../../crates/infra" }
sa-monopoly-domain = { path = "../../crates/domain" }
serde_json = "1"
log = "0.4"
